""" The AKMA unit system is employed, it uses the following reduced units:
    Angle = "RADIAN"
    Length = "ANGSTROM"
    Mass = "DALTON"
    Charge = "ELECTRON_CHARGE"
    Energy = "KCAL_MOL"
    Time = AKMA
    Temperature = "KELVIN"
"""

# base units
RADIAN = 1.
ANGSTROM = 1.
DALTON = 1.
ELECTRON_CHARGE = 1.
AKMA = 1.

# dimensionless constants
PI = 3.141592653589793
AVOGADRO = 6.022141179e23
NA = AVOGADRO
MOLE = AVOGADRO
MOL = AVOGADRO
RAD = RADIAN
DEGREE = PI / 180.
FINE_STRUCTURE = 7.2973525698e-3
ALPHA = FINE_STRUCTURE
RAD2DEG = 180. / PI
DEG2RAD = PI / 180.

# length
METER = 1e10 * ANGSTROM
M = METER
CENTIMETER = 1e-2 * METER
CM = CENTIMETER
MILLIMETER = 1e-3 * METER
MM = MILLIMETER
MICROMETER = 1e-6 * METER
UM = MICROMETER
NANOMETER = 1e-9 * METER
NM = NANOMETER
PICOMETER = 1e-12 * METER
PM = PICOMETER
FEMTOMETER = 1e-15 * METER
FM = FEMTOMETER

# mass
AMU = DALTON
KILOGRAM = DALTON / 1.660538921e-27
KG = KILOGRAM
GRAM = 1e-3 * KILOGRAM
ELECTRON_MASS = DALTON / 1822.88839
ELECTRON_M = ELECTRON_MASS
M_E = ELECTRON_MASS

# charge
ELECTRON_Q = ELECTRON_CHARGE
Q_E = ELECTRON_CHARGE
COULOMB = 1. / 1.60217646e-19

# energy
KCAL_MOL = 1.
KCAL = MOL
CALORIE = KCAL * 1e-3
CAL = CALORIE
JOULE = CAL / 4.184
J = JOULE
KJOULE = JOULE * 1e3
KJ = KJOULE
KJOULE_MOL = KJOULE / MOL
KJ_MOL = KJOULE_MOL
ELECTRONVOLT = JOULE / COULOMB
EV = ELECTRONVOLT
ERG = JOULE * 1e-7
# more energy units defined below
# RY
# WAVENUMBER
# HARTREE

# voltage
VOLT = JOULE / COULOMB

# capacitance
FARAD = JOULE / VOLT**2

# time
SECOND = (KG * METER**2 / JOULE)**0.5
S = SECOND
MILLISECOND = 1e-3 * SECOND
MS = MILLISECOND
MICROSECOND = 1e-6 * SECOND
US = MICROSECOND
NANOSECOND = 1e-9 * SECOND
NS = NANOSECOND
PICOSECOND = 1e-12 * SECOND
PS = PICOSECOND
FEMTOSECOND = 1e-15 * SECOND
FS = FEMTOSECOND

# constants
BOLTZMANN = 1.3806488e-23 * JOULE # units of J/K
K_B = BOLTZMANN
KB = BOLTZMANN
LIGHTSPEED = 299792458 * METER / SECOND
C = LIGHTSPEED
PLANCK = 6.62606957e-34 * JOULE * SECOND
H = PLANCK
HBAR = PLANCK / (2 * PI)
VACUUM_PERMITTIVITY = ELECTRON_CHARGE**2 / (2 * FINE_STRUCTURE * PLANCK * LIGHTSPEED)
EPSILON_0 = VACUUM_PERMITTIVITY
EPS0 = VACUUM_PERMITTIVITY
RYDBERG_CON = ELECTRON_MASS * ELECTRON_CHARGE**4 / (8 * VACUUM_PERMITTIVITY**2 * PLANCK**3 * LIGHTSPEED)
R_INF = RYDBERG_CON
R_H = RYDBERG_CON

# dipole
DEBYE = 1e-21 * COULOMB * METER**2 / SECOND / LIGHTSPEED

# more energy
WAVENUMBER = PLANCK * LIGHTSPEED / CENTIMETER
RYDBERG_E = PLANCK * LIGHTSPEED * RYDBERG_CON
RY = RYDBERG_E
HARTREE = 2 * RYDBERG_E

# force
NEWTON = KILOGRAM * METER / SECOND**2
N = NEWTON

# pressure
PASCAL = NEWTON / METER**2
PA = PASCAL
BAR = 1e5 * PASCAL
ATM = 1.01325e5 * PASCAL
TORR = 133.3224 * PASCAL
PSI = 6.8948e3 * PASCAL

# frequency
HERTZ = 1 / SECOND
HZ = HERTZ

# current
AMPERE = COULOMB / SECOND
AMP = AMPERE

# angular frequency
#ANG_FREQ = 18.836e10 RAD/S

# volume
MILLILITER = CENTIMETER**3
LITER = 1e3 * MILLILITER

# temperature
KELVIN = 1.
K = KELVIN
def to_celcius(t):
    return t + 273.15

